apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cloudnative-pg-chart
  namespace: kube-system
spec:
  repo: https://cloudnative-pg.github.io/charts
  chart: cloudnative-pg
  version: 0.23.0
  targetNamespace: kube-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-operator-crds-chart
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-operator-crds
  version: 17.0.2
  targetNamespace: kube-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: csi-driver-smb-chart
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  chart: csi-driver-smb
  version: v1.16.0
  targetNamespace: kube-system
