---
- name: Bootstrap all proxmox nodes
  hosts: all
  roles:
    - role: proxmox_node
      tags:
        - proxmox_node

- name: Install NUT
  hosts: all
  roles:
    - role: on_prem_power
      tags:
        - on_prem_power
