---
- name: Expand disks of Proxmox VMs
  hosts: docker_containers_group:dev_playground
  roles:
    - role: potentially_small_disk
      tags:
        - potentially_small_disk

- name: Bootstrap all machines
  hosts: all
  roles:
    - role: internal_dns
      tags:
        - internal_dns
    - role: certificates
      tags:
        - certificates
    - role: ssh_server
      tags:
        - ssh_server

- name: Configure VPS
  hosts: vps
  gather_facts: true
  roles:
    - role: vps
      tags:
        - vps

- name: Configure Docker Containers
  hosts: docker_containers_group
  pre_tasks:
    - ansible.builtin.set_fact:
        ansible_distribution_version: "{{ inventory_hostname is search('zotac*') ? ansible_distribution_version.split('.')[0] : ansible_distribution_version }}"
  tasks:
    - name: Docker Containers role
      include_role:
        name: docker_containers
      tags:
        - docker_containers

- name: Configure dev playground
  hosts: dev_playground_group
  roles:
    - role: dev_playground
      tags:
        - dev_playground

- name: Configure VPN server
  hosts: vps
  roles:
    - role: vpn_server
      tags:
        - vpn_server

- name: Configure VPN clients
  hosts: docker_containers_group[0]
  roles:
    - role: vpn_client
      tags: 
        - vpn_client
