---
- name: Bootstrap all machines
  hosts: proxmox_all:vps
  roles:
    - internal_dns
    - certificates
    - ssh_server

- name: Add QEMU guest agent
  hosts: proxmox_all
  roles:
    - qemu

- name: Configure VPS
  hosts: vps
  gather_facts: true
  roles:
    - vps

- name: Configure Docker Containers
  hosts: docker_containers_group
  roles:
    - docker_containers

- name: Configure dev playground
  hosts: dev_playground_group
  roles:
    - dev_playground

- name: Configure vault
  hosts: vault_group
  roles:
    - vault
