---
- name: Bootstrap all machines
  hosts: all
  roles:
    - role: internal_dns
      tags:
        - internal_dns
    - role: certificates
      tags:
        - certificates
    - role: ssh_server
      tags:
        - ssh_server

- name: Install NUT
  hosts: all
  roles:
    - role: on_prem_power
      tags:
        - on_prem_power
