roles:
  - src: rvm.ruby
  - name: ansible-role-nvm
    src: https://github.com/morgangraphics/ansible-role-nvm
  - src: nvjacobo.caddy
  - src: kyl191.openvpn
  - src: geerlingguy.docker
  - src: gantsign.oh-my-zsh
collections:
  - ansible.posix
  - community.general
  - community.docker
  - manala.roles
