dependencies:
  - role: geerlingguy.swap
    become: true
    vars:
      swap_file_state: absent
  - role: geerlingguy.containerd
    become: true
  - role: uchida.nvidia-container-runtime
    when: inventory_hostname is search('zotac*')
    vars:
      ansible_distribution_version: "{{ ansible_distribution_version.split('.')[0] }}"
    become: true
  - role: xanmanning.k3s
    vars:
      k3s_become: true
      k3s_agent:
        with-node-id: true
        node-label: "{% if inventory_hostname is search('zotac*') %}['gpu_instance={{ inventory_hostname }}']{% else %}[]{% endif %}"
      
