---
- name: Install required system packages
  apt:
    pkg:
      - git
    state: latest
    update_cache: true

- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/jpitlor/.files'
    dest: '{{ DOTFILES_FOLDER }}'
    version: '{{ DOTFILES_REPO_COMMIT }}'

# TODO - symlink all the files
