---
- name: Install required system packages
  apt:
    pkg:
      - openvpn
      - openvpn-systemd-resolvd
    state: latest
    update_cache: true

# TODO - somehow generate ta.key and ca.key and obtain client.crt and client.key

- name: Write ovpn file
  ansible.builtin.template:
    src: client.ovpn.j2
    dest: /etc/dev.pitlor/client.ovpn

- name: Add OpenVPN autoconnect cronjob
  ansible.builtin.copy:
    src: "cron-vpn-connect"
    dest: "/etc/cron.d/cron-vpn-connect"
