---
- name: Install required system packages
  become: true
  apt:
    pkg:
      - openvpn
    state: latest
    update_cache: true

- name: Copy VPN client files
  become: true
  ansible.builtin.copy:
    src: "./openvpn_client_files/{{ inventory_hostname }}-{{ groups['vps'][0] }}.ovpn"
    dest: "/etc/openvpn/client/vps.conf"

- name: Enable OpenVPN service
  become: true
  ansible.builtin.service:
    name: openvpn-client@vps
    enabled: true
    state: started
