---
- name: Create homelab namespace
  run_once: true
  kubernetes.core.k8s:
    name: '{{ kubernetes_homelab_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Install CRD dependencies
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cloudnative-pg-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://cloudnative-pg.github.io/charts
          chart: cloudnative-pg
          version: 0.26.0
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: prometheus-operator-crds-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://prometheus-community.github.io/helm-charts
          chart: prometheus-operator-crds
          version: 17.0.2
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: csi-driver-smb-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
          chart: csi-driver-smb
          version: v1.16.0
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cert-manager-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          chart: oci://quay.io/jetstack/charts/cert-manager
          version: v1.18.2
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
          valuesContent: |-
            crds:
              enabled: true
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: velero
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          chart: velero
          repo: https://vmware-tanzu.github.io/helm-charts
          version: 12.0.0
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
          valuesContent: |-
            credentials:
              secretContents:
                cloud: {{ velero_service_account_json | quote }}
            snapshotsEnabled: false
            metrics:
              enabled: true
              scrapeInterval: 30s
            deployNodeAgent: true
            configuration:
              features: EnableCSI
              backupStorageLocation:
                - name: "gcs-backup-location"
                  provider: "gcp"
                  bucket: "dev-pitlor-homelab-velero_backups"
              defaultBackupStorageLocation: "gcs-backup-location"
            initContainers:
              - name: velero-plugin-for-gcp
                image: velero/velero-plugin-for-gcp:v1.8.0
                volumeMounts:
                  - mountPath: /target
                    name: plugins
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: feature-discovery-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
          chart: node-feature-discovery
          version: v0.18.3
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: nvidia-k8s-device-plugin-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://nvidia.github.io/k8s-device-plugin
          chart: nvidia-device-plugin
          version: v0.18.2
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
          valuesContent: |-
            runtimeClassName: nvidia
            gfd:
              enabled: true
      - apiVersion: v1
        kind: Secret
        metadata:
          name: longhorn-gcp-credentials
          namespace: homelab
          type: Opaque
        stringData:
          AWS_ACCESS_KEY_ID: "{{ longhorn_gcp_key }}"
          AWS_SECRET_ACCESS_KEY: "{{ longhorn_gcp_secret }}"
          AWS_ENDPOINTS: https://storage.googleapis.com
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: longhorn-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://charts.longhorn.io
          chart: longhorn
          version: v1.11.1
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
          valuesContent: |-
            namespaceOverride: '{{ kubernetes_homelab_namespace }}'
            persistence:
              defaultClass: false
            service:
              ui:
                type: NodePort
            defaultSettings:
              createDefaultDiskLabeledNodes: true
              storageReservedPercentageForDefaultDisk: 15
              storageMinimalAvailablePercentage: 15
              orphanResourceAutoDeletion: ""
              orphanResourceAutoDeletionGracePeriod: 300
            defaultBackupStore:
              backupTarget: s3://dev-pitlor-homelab-longhorn_backups@us-central1/
              backupTargetCredentialSecret: longhorn-gcp-credentials

- name: Pause for Cert Manager to install
  ansible.builtin.pause:
    seconds: 90

- name: Download barman cloud plugin
  run_once: true
  ansible.builtin.get_url:
    url: https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.6.0/manifest.yaml
    dest: ~/barman-cloud-plugin.yaml
    mode: '0664'

- name: Put proper namespace in barman cloud plugin
  run_once: true
  ansible.builtin.replace:
    path: ~/barman-cloud-plugin.yaml
    regexp: 'cnpg-system'
    replace: '{{ kubernetes_homelab_namespace }}'

- name: Apply barman cloud plugin manifest to the cluster.
  run_once: true
  kubernetes.core.k8s:
    state: present
    src: ~/barman-cloud-plugin.yaml

- name: Add NAS credentials
  run_once: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ nas_credentials_name }}"
        namespace: homelab
      stringData:
        username: "{{ nas_username }}"
        password: "{{ lookup('ansible.builtin.env', 'NAS_PASSWORD') }}"

- name: Add NAS storage classes
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: "{{ item.name }}"
        namespace: homelab
      provisioner: smb.csi.k8s.io
      parameters:
        source: "//{{ nas_ip_address }}/{{ item.shareName }}/"
        subDir: "{{ '${pvc.metadata.name}' if item.enableProvisioner else omit }}"
        csi.storage.k8s.io/provisioner-secret-name: "{{ nasCredentialsName if item.enableProvisioner else omit }}"
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ 'homelab' if item.enableProvisioner else omit }}"
        csi.storage.k8s.io/node-stage-secret-name: "{{ nasCredentialsName }}"
        csi.storage.k8s.io/node-stage-secret-namespace: homelab
      reclaimPolicy: "{{ item.reclaimPolicy }}"
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      mountOptions:
        - dir_mode=0{{ item.mode }}
        - file_mode=0{{ item.mode }}
        - uid={{ item.uid }}
        - gid={{ item.uid }}
  loop:
    - name: nas
      mode: 777
      uid: 1000
      shareName: Homelab
      reclaimPolicy: Delete
      enableProvisioner: true
    - name: nextcloud
      mode: 770
      uid: 33
      shareName: Documents
      reclaimPolicy: Retain
      enableProvisioner: false
    - name: media
      mode: 770
      uid: 1000
      shareName: Media
      reclaimPolicy: Retain
      enableProvisioner: false
    - name: ingest
      mode: 770
      uid: 1000
      shareName: Ingest
      reclaimPolicy: Delete
      enableProvisioner: true

- name: Add Longhorn storage classes
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: "{{ item.name }}"
        annotations:
          "storageclass.kubernetes.io/is-default-class": "{{ item.isDefault }}"
      provisioner: driver.longhorn.io
      parameters:
        numberOfReplicas: "{{ item.replicas }}"
  loop:
    - name: ssd
      replicas: 2
      isDefault: false
    - name: ssd-large
      replicas: 1
      isDefault: true

- name: Install homelab chart
  run_once: true
  tags:
    - homelab_chart
  vars:
    postgres_values:
      grafana: 
        postgres: &db_params
          backupId: "{{ homelab_chart_backup_id | default(omit) }}"
          recoverFromBackupId: "{{ homelab_chart_restore_from_backup_id | default(omit) }}"
          recoverFromBackupTime: "{{ homelab_chart_restore_from_backup_time | default(omit) }}"
      vaultwarden: 
        postgres: *db_params
      immich: 
        postgres: *db_params
      nextcloud: 
        postgres: *db_params
      gitea: 
        postgres: *db_params
      infisical-standalone: 
        postgres: *db_params
      guacamole: 
        postgres: *db_params
      mealie: 
        postgres: *db_params
      coder: 
        postgres: *db_params
      authentik: 
        postgres: *db_params
      dawarich: 
        postgres: *db_params
      open-webui: 
        postgres: *db_params
      homebox: 
        postgres: *db_params
      open-archiver: 
        postgres: *db_params
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: homelab-chart
        namespace: '{{ kubernetes_homelab_namespace }}'
      spec:
        chart: oci://us-central1-docker.pkg.dev/dev-pitlor-homelab/homelab-chart/homelab-containers
        version: '{{ homelab_chart_version }}'
        targetNamespace: '{{ kubernetes_homelab_namespace }}'
        valuesContent: |-
          google:
            serviceAccountJson: {{ lookup('ansible.builtin.env', 'POSTGRES_SERVICE_ACCOUNT_JSON') | quote }}

          nas:
            password: {{ lookup('ansible.builtin.env', 'NAS_PASSWORD') | quote }}

          blueskyPds:
            jwtSecret: {{ lookup('ansible.builtin.env', 'BLUESKY_JWT_SECRET') | quote }}
            adminPassword: {{ lookup('ansible.builtin.env', 'BLUESKY_ADMIN_PASSWORD') | quote }}
            plcRotationKey: {{ lookup('ansible.builtin.env', 'BLUESKY_PLC_ROTATION_KEY') | quote }}

          infisical:
            encryptionKey: {{ lookup('ansible.builtin.env', 'INFISICAL_ENCRYPTION_KEY') | quote }}
            authSecret: {{ lookup('ansible.builtin.env', 'INFISICAL_AUTH_SECRET') | quote }}   

          postfix:
            username: {{ lookup('ansible.builtin.env', 'POSTFIX_USERNAME') | quote }}  
            password: {{ lookup('ansible.builtin.env', 'POSTFIX_PASSWORD') | quote }}  

          openArchiver:
            meiliMasterKey: {{ lookup('ansible.builtin.env', 'OPEN_ARCHIVER_MEILI_MASTER_KEY') | quote }}  
            jwtSecret: {{ lookup('ansible.builtin.env', 'OPEN_ARCHIVER_JWT_SECRET') | quote }}  
            encryptionKey: {{ lookup('ansible.builtin.env', 'OPEN_ARCHIVER_ENCRYPTION_KEY') | quote }}  

          sunshine:
            password: {{ lookup('ansible.builtin.env', 'SUNSHINE_PASSWORD') | quote }}

          applications: 
            {{ postgres_values | to_nice_yaml(indent=2) | indent(2) }}
