---
- name: Create kube folder
  become: true
  ansible.builtin.file:
    path: "/home/{{ username }}/.kube"
    state: directory

- name: Symlink kubeconfig
  become: true
  ansible.builtin.file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ username }}/.kube/config"
    owner: "{{ username }}"
    state: link

- name: Install required system packages
  become: true
  apt:
    pkg:
      - python3-pip
      - python3
    state: latest
    update_cache: true

- name: Install pip requirements
  community.general.pipx:
    name: "{{ item.name }}"
    state: present
  loop:
    - pyyaml==3.11
    - kubernetes==24.2.0
    - jsonpatch==1.33

- name: Install CRD dependencies
  kubernetes.core.k8s:
    state: present
    src: homelab-chart-dependencies.yaml

- name: Clone Chart
  ansible.builtin.git:
    repo: 'https://github.com/jpitlor/homelab-chart'
    dest: '{{ homelab_data_folder }}/homelab-chart'

- name: Deploy Homelab Chart
  kubernetes.core.helm:
    chart_ref: '{{ homelab_data_folder }}/homelab-chart'
    name: homelab
    release_namespace: '{{ kubernetes_homelab_namespace }}'
    create_namespace: true
    dependency_update: true
