---
- name: Create kube folder
  become: true
  ansible.builtin.file:
    path: "/home/{{ username }}/.kube"
    state: directory

- name: Symlink kubeconfig
  become: true
  ansible.builtin.file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ username }}/.kube/config"
    owner: "{{ username }}"
    state: link

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-yaml
      - python3-kubernetes
      - python3-jsonpatch
    state: latest
    update_cache: true

- name: Install required system packages
  become: true
  apt:
    pkg:
      - python3-pip
      - python3
    state: latest
    update_cache: true

# NOTE: Because these are libraries and not applications, pipx will not work,
#       and the versions of these libraries on apt are outdated, so pip with
#       the --break-system-packages flag is the best way of doing this for now
- name: Install python dependencies
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--break-system-packages"
  loop:
    - pyyaml==3.11
    - kubernetes==24.2.0
    - jsonpatch==1.33

- name: Create homelab namespace
  kubernetes.core.k8s:
    name: '{{ kubernetes_homelab_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Install CRD dependencies
  kubernetes.core.k8s:
    state: present
    definition:
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cloudnative-pg-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://cloudnative-pg.github.io/charts
          chart: cloudnative-pg
          version: 0.23.0
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: prometheus-operator-crds-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://prometheus-community.github.io/helm-charts
          chart: prometheus-operator-crds
          version: 17.0.2
          targetNamespace: '{{ kubernetes_homelab_namespace }}'
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: csi-driver-smb-chart
          namespace: '{{ kubernetes_homelab_namespace }}'
        spec:
          repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
          chart: csi-driver-smb
          version: v1.16.0
          targetNamespace: '{{ kubernetes_homelab_namespace }}'

- name: Install homelab chart
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: homelab-chart
        namespace: '{{ kubernetes_homelab_namespace }}'
      spec:
        chart: oci://us-central1-docker.pkg.dev/dev-pitlor-homelab/homelab-chart/homelab-containers
        version: 1.0.3
        targetNamespace: '{{ kubernetes_homelab_namespace }}'
