---
- name: Clone Chart
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/jpitlor/homelab-chart'
    dest: '{{ homelab_data_folder }}/homelab-chart'

- name: Deploy Chart
  kubernetes.core.helm:
    ref: '{{ homelab_data_folder }}/homelab-chart'
    release_namespace: '{{ kubernetes_homelab_namespace }}'
    create_namespace: true
