---
- name: Fail if neccessary environment variables are missing
  ansible.builtin.fail:
    msg: "Environment variable {{ item }} is missing"
  when: item is falsy
  loop:
    - lookup('ansible.builtin.env', 'NAS_PASSWORD')
    - lookup('ansible.builtin.env', 'BLUESKY_JWT_SECRET')
    - lookup('ansible.builtin.env', 'BLUESKY_ADMIN_PASSWORD')
    - lookup('ansible.builtin.env', 'BLUESKY_PLC_ROTATION_KEY')
    - lookup('ansible.builtin.env', 'BLUESKY_EMAIL_SMTP_URL')
    - lookup('ansible.builtin.env', 'INFISICAL_ENCRYPTION_KEY')
    - lookup('ansible.builtin.env', 'INFISICAL_AUTH_SECRET')
    - lookup('ansible.builtin.env', 'TANDOOR_SECRET_KEY')

- name: Set up Kubernetes
  ansible.builtin.include_tasks: "k3s_system.yml"

- name: Add resources to Kubernetes
  ansible.builtin.include_tasks: "k3s_resources.yml"
