---
- name: Create /var/dev.pitlor
  become: true
  ansible.builtin.file:
    path: /var/dev.pitlor
    state: directory

- name: Clone Chart
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/jpitlor/homelab-chart'
    dest: '{{ CONTAINER_CONFIG_FOLDER }}'

- name: Deploy Chart
  kubernetes.core.helm:
    ref: '{{ CONTAINER_CONFIG_FOLDER }}'
    release_namespace: homelab
    create_namespace: true
