---
- name: Create kube folder
  become: true
  ansible.builtin.file:
    path: "/home/{{ username }}/.kube"
    state: directory

- name: Symlink kubeconfig
  become: true
  ansible.builtin.file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ username }}/.kube/config"
    owner: "{{ username }}"
    state: link

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-yaml
      - python3-kubernetes
      - python3-jsonpatch
    state: latest
    update_cache: true

- name: Install required system packages
  become: true
  apt:
    pkg:
      - python3-pip
      - python3
    state: latest
    update_cache: true

# NOTE: Because these are libraries and not applications, pipx will not work,
#       and the versions of these libraries on apt are outdated, so pip with
#       the --break-system-packages flag is the best way of doing this for now
- name: Install python dependencies
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--break-system-packages"
  loop:
    - pyyaml==3.11
    - kubernetes==24.2.0
    - jsonpatch==1.33

- name: Install CRD dependencies
  kubernetes.core.k8s:
    state: present
    src: "{{ lookup('file', 'homelab-chart-dependencies.yaml') | from_yaml_all }}"

- name: Clone Chart
  ansible.builtin.git:
    repo: 'https://github.com/jpitlor/homelab-chart'
    dest: '{{ homelab_data_folder }}/homelab-chart'

- name: Deploy Homelab Chart
  kubernetes.core.helm:
    chart_ref: '{{ homelab_data_folder }}/homelab-chart'
    name: homelab
    release_namespace: '{{ kubernetes_homelab_namespace }}'
    create_namespace: true
    dependency_update: true
