---
- name: Fail if neccessary environment variables are missing
  ansible.builtin.fail:
    msg: "Environment variable {{ item }} is missing"
  when: lookup('ansible.builtin.env', item) is falsy
  loop:
    - 'NAS_PASSWORD'
    - 'BLUESKY_JWT_SECRET'
    - 'BLUESKY_ADMIN_PASSWORD'
    - 'BLUESKY_PLC_ROTATION_KEY'
    - 'INFISICAL_ENCRYPTION_KEY'
    - 'INFISICAL_AUTH_SECRET'
    - 'POSTGRES_SERVICE_ACCOUNT_JSON'
    - 'POSTFIX_USERNAME'
    - 'POSTFIX_PASSWORD'
    - 'OPEN_ARCHIVER_MEILI_MASTER_KEY'
    - 'OPEN_ARCHIVER_JWT_SECRET'
    - 'OPEN_ARCHIVER_ENCRYPTION_KEY'
    - 'SUNSHINE_PASSWORD'

- name: Install packages
  ansible.builtin.include_tasks: "01_packages.yml"

- name: Install CRDs
  ansible.builtin.include_tasks: "02_crds.yml"

- name: Add GPU capabilities
  ansible.builtin.include_tasks: "03_gpu.yml"

- name: Add storage classes
  ansible.builtin.include_tasks: "04_storage.yml"

- name: Add backups/restores
  ansible.builtin.include_tasks: "05_disaster_recovery.yml"

- name: Add applications
  ansible.builtin.include_tasks: "06_applications.yml"
