---
- name: Install required system packages
  apt:
    pkg:
      - openvpn
    state: latest
    update_cache: true

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: "Copy OpenVPN config"
  when: ansible_facts['os_family'] != "Windows"
  ansible.builtin.copy:
    src: "server.conf"
    dest: "/etc/openvpn/server/server.conf"

- name: Enable OpenVPN service
  ansible.builtin.systemd_service:
    name: openvpn-server@server.service
    state: started
    enabled: true
