---

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg2
    state: latest
    update_cache: true

- name: Add non-free repository
  become: true
  ansible.builtin.deb822_repository:
    name: debian
    uris: "http://ftp.us.debian.org/debian/"
    suites: ["bookworm"]
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware

- name: Add nvidia repository
  become: true
  ansible.builtin.deb822_repository:
    name: nvidia-container
    uris: "https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)"
    signed_by: https://nvidia.github.io/libnvidia-container/gpgkey
    suites: ["/"]

- name: Copy version pin
  become: true
  ansible.builtin.copy:
    src: nvidia-pin
    dest: /etc/apt/preferences.d/nvidia-pin

- name: Install linux headers
  become: true
  ansible.builtin.apt:
    pkg:
      - linux-headers-generic
    state: latest
    update_cache: true

- name: Install drivers and container runtime
  become: true
  ansible.builtin.apt:
    pkg:
      - firmware-misc-nonfree
      - nvidia-driver=580.126.20-1
      - nvtop
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
      - libnvidia-container-tools
      - libnvidia-container1
      - nvidia-container-runtime 
      - cuda-drivers
    state: latest
    update_cache: true

- name: Configure runtime
  become: true
  ansible.builtin.shell: nvidia-ctk runtime configure --runtime=containerd

- name: Restart 
  become: true
  ansible.builtin.reboot:
