---

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg2
    state: latest
    update_cache: true

- name: Add nvidia repository
  become: true
  ansible.builtin.deb822_repository:
    name: nvidia-container
    uris: "https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)"
    signed_by: https://nvidia.github.io/libnvidia-container/gpgkey
    suites: ["/"]

- name: Install drivers and container runtime
  become: true
  ansible.builtin.apt:
    pkg:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
      - libnvidia-container-tools
      - libnvidia-container1
      - nvidia-container-runtime 
    state: latest
    update_cache: true

- name: Configure runtime
  become: true
  ansible.builtin.shell: nvidia-ctk runtime configure --runtime=containerd

- name: Restart containerd
  become: true
  ansible.builtin.shell: systemctl restart containerd
