---
- name: Install required system packages
  become: true
  apt:
    pkg:
      - git
      - vim
      - build-essential
      - wget
      - sl
      - toilet
      - cowsay
      - fortune
      - imagemagick
      - x11-apps
      - dnsutils
      - python3-venv
      - python3
    state: latest
    update_cache: true
