---
- name: "Create homelab group"
  become: true
  ansible.builtin.group:
    name: "{{ homelab_group_name }}"
    state: present

- name: "Add users to homelab group"
  become: true
  ansible.builtin.user:
    groups: "{{ homelab_group_name }}"
    append: true
    name: '{{ username }}'

- name: "Create homelab data folder"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.file:
    path: '{{ homelab_data_folder }}'
    state: directory
    owner: root
    group: '{{ homelab_group_name }}'
    mode: '0775'

- name: "Copy SSH CA"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "pitlor-ssh-ca.pub"
    dest: "{{ homelab_data_folder }}/pitlor-ssh-ca.pub"
    owner: root
    group: "{{ homelab_group_name }}"

- name: "Set SSH security"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "200-sshd-security.conf"
    dest: "/etc/ssh/sshd_config.d/200-sshd-security.conf"
    owner: root
    group: "{{ homelab_group_name }}"

- name: "Trust SSH CA"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.template:
    src: "201-sshd-pitlor-ca.conf.j2"
    dest: "/etc/ssh/sshd_config.d/201-sshd-pitlor-ca.conf"
    owner: root
    group: "{{ homelab_group_name }}"

- name: Restart SSH
  become: true
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Give no password sudo access
  become: true
  ansible.builtin.template:
    src: "passwordless-sudo.j2"
    dest: "/etc/sudoers.d/{{ username }}"
    owner: root
    group: "{{ homelab_group_name }}"

- name: Install system packages
  become: true
  apt:
    pkg:
      - vim
      - wget
      - curl
      - tmux
      - python3-launchpadlib
      - build-essential
      - lsof
      - telnet
      - jq
      - cloud-utils
    state: latest
    update_cache: true

- name: Install Oh My ZSH Theme
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/moarram/headline/main/headline.zsh-theme
    dest: /usr/local/share/oh-my-zsh/themes

- name: Install Vundle
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '/home/{{ username }}/.vim/bundle/Vundle.vim'
    version: '{{ vundle_git_commit }}'

- name: Clone dotfiles
  become: true
  ansible.builtin.git:
    force: true
    repo: 'https://github.com/jpitlor/.files'
    dest: '{{ homelab_data_folder }}/.files'
    version: '{{ dotfiles_git_commit }}'

#- name: Add dotfiles autoupdate cronjob
#  when: ansible_facts['os_family'] != "Windows"
#  become: true
#  ansible.builtin.copy:
#    src: "cron-dotfiles-auto-update"
#    dest: "/etc/cron.d/cron-dotfiles-auto-update"

- name: Discover dotfiles
  ansible.builtin.find:
    paths: '{{ homelab_data_folder }}/.files'
    patterns: '.*'
    hidden: true
  register: dotfiles

- name: "Symlink dot files"
  become: true
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "/home/{{ username }}/{{ item.path | basename }}"
    state: link
    owner: root
    group: "{{ homelab_group_name }}"
    mode: '774'
    force: true
  loop: "{{ dotfiles.files }}"

- name: Install Vundle plugins
  become: true
  ansible.builtin.command: vim +PluginInstall +qall
