---
- name: "Create /etc/dev.pitlor"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.file:
    path: /etc/dev.pitlor
    state: directory

- name: "Create homelab group"
  ansible.builtin.group:
    name: homelab
    state: present

- name: "Add users to homelab group"
  ansible.builtin.user:
    groups: homelab
    append: true
    name: jpitlor

- name: "Copy SSH CA"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "pitlor-ssh-ca.pub"
    dest: "/etc/dev.pitlor/pitlor-ssh-ca.pub"

- name: "Set SSH security"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "200-sshd-security.conf"
    dest: "/etc/ssh/sshd_config.d/200-sshd-security.conf"

- name: "Trust SSH CA"
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "201-sshd-pitlor-ca.conf"
    dest: "/etc/ssh/sshd_config.d/201-sshd-pitlor-ca.conf"

- name: Restart SSH
  become: true
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Give no password sudo access
  become: true
  ansible.builtin.copy:
    src: "sudoers-jpitlor"
    dest: "/etc/sudoers.d/jpitlor"

- name: Install system packages
  become: true
  apt:
    pkg:
      - git
      - vim
      - wget
      - curl
      - zsh
      - tmux
    state: latest
    update_cache: true

- name: Install Oh My ZSH
  become: true
  ansible.builtin.import_role:
    name: manala.roles.ohmyzsh
  vars:
    manala_ohmyzsh_users:
      - user: jpitlor
  register: ohmyzsh

- name: See if .zshrc is generated
  ansible.builtin.stat:
    path: /home/jpitlor/.zshrc
  register: zshrc_stat

- name: Remove generated .zshrc
  ansible.builtin.file:
    path: /home/jpitlor/.zshrc
    state: absent
  when: not zshrc_stat.stat.islnk

- name: Install Oh My ZSH Theme
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/moarram/headline/main/headline.zsh-theme
    dest: /usr/local/share/oh-my-zsh/themes

- name: Install Vundle
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '/home/jpitlor/.vim/bundle/Vundle.vim'
    version: '{{ VUNDLE_COMMIT }}'

- name: Clone dotfiles
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/jpitlor/.files'
    dest: '{{ DOTFILES_FOLDER }}'
    version: '{{ DOTFILES_REPO_COMMIT }}'

- name: Add dotfiles autoupdate cronjob
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "cron-dotfiles-auto-update"
    dest: "/etc/cron.d/cron-dotfiles-auto-update"

- name: "Symlink {{ item }}"
  become: true
  ansible.builtin.file:
    src: "{{ DOTFILES_FOLDER }}/{{ item }}"
    dest: "/home/{{ USER }}/{{ item }}"
    state: link
    owner: root
    group: "{{ USER }}"
    mode: '774'
  loop: "{{ DOTFILES }}"

- name: Install Vundle plugins
  ansible.builtin.command: vim +PluginInstall +qall
