---
- name: "Trust {{ item.name }}"
  when: ansible_facts['os_family'] != "Windows"
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "/etc/ssl/certs/{{ item.file }}"
  loop: certs

- name: "Trust {{ item.name }}"
  when: ansible_facts['os_family'] == "Windows"
  ansible.windows.win_certificate_store:
    path: "{{ item.file }}"
    state: present
    key_exportable: false
  loop: certs

