---
- name: Trust certificates (Unix)
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "/etc/ssl/certs/{{ item.file }}"
  loop: "{{ trusted_certificates }}"

- name: Trust certificates (Windows)
  when: ansible_facts['os_family'] == "Windows"
  become: true
  ansible.windows.win_certificate_store:
    path: "{{ item.file }}"
    state: present
    key_exportable: false
  loop: "{{ trusted_certificates }}"


- name: Get infisical apt key
  become: true
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/infisical/infisical-cli/gpg.2E8A3D44C97EAED6.key
    dest: /usr/share/keyrings/infisical-infisical-cli-archive-keyring.gpg

- name: Add infisical repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }} [signed-by=/usr/share/keyrings/infisical-infisical-cli-archive-keyring.gpg] https://dl.cloudsmith.io/public/infisical/infisical-cli/deb/any-distro any-version main"
    state: present
  loop:
    - deb
    - deb-src

- name: Install infisical CLI
  become: true
  apt:
    pkg:
      - infisical
    state: latest
    update_cache: true

    