---
- name: Install necessary packages
  become: true
  apt:
    pkg:
      - python3-debian
    state: latest
    update_cache: true

- name: Trust certificates (Unix)
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "/etc/ssl/certs/{{ item.file }}"
  loop: "{{ trusted_certificates }}"

- name: Trust certificates (Windows)
  when: ansible_facts['os_family'] == "Windows"
  become: true
  ansible.windows.win_certificate_store:
    path: "{{ item.file }}"
    state: present
    key_exportable: false
  loop: "{{ trusted_certificates }}"

- name: Add infisical repository
  become: true
  ansible.builtin.deb822_repository:
    name: infisicial-infisical-cli
    uris: https://dl.cloudsmith.io/public/infisical/infisical-cli/deb/ubuntu
    suites: [jammy]
    components: [main]
    signed_by: https://dl.cloudsmith.io/public/infisical/infisical-cli/gpg.2E8A3D44C97EAED6.key

- name: Install infisical CLI
  become: true
  apt:
    pkg:
      - infisical
    state: latest
    update_cache: true

    