---
- name: Set Windows hosts
  when: ansible_facts['os_family'] == "Windows"
  community.windows.win_hosts:
    state: present
    canonical_name: "{{ item }}"
    ip_address: '10.1.0.7'
    loop: domains
- name: Set Linux hosts
  when: ansible_facts['os_family'] != "Windows"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "10.1.0.7 {{ item }}"
    state: present
    loop: domains

