---
- name: Set hosts (Windows)
  when: ansible_facts['os_family'] == "Windows"
  become: true
  community.windows.win_hosts:
    state: present
    canonical_name: "{{ item }}"
    ip_address: "{{ docker_host_vpn_ip }}"
  loop: "{{ internal_service_domains }}"

- name: Set hosts (Unix)
  when: ansible_facts['os_family'] != "Windows"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ docker_host_vpn_ip }} {{ item }}"
    state: present
  loop: "{{ internal_service_domains }}"

