---
- name: Set Windows hosts
  when: ansible_facts['os_family'] == "Windows"
  community.windows.win_hosts:
    state: present
    canonical_name: "{{ item }}"
    ip_address: "{{ docker_host_vpn_ip }}"
    loop: domains

- name: Set Linux hosts
  when: ansible_facts['os_family'] != "Windows"
  `ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ docker_host_vpn_ip }} {{ item }}"
    state: present`
    loop: domains

