---
- name: Install system packages
  become: true
  apt:
    pkg:
      - parted
    state: latest
    update_cache: true

# - name: "Read partition info"
#   become: true
#   community.general.parted: 
#     device: /dev/sda
#   register: sda_info

- name: "Extend partition"
  become: true
  community.general.parted:
    device: /dev/sda
    number: 5
    part_end: "100%"
    resize: true
    state: present

- name: "Expand logical volume and resize filesystem"
  become: true
  community.general.lvol:
    vg: debian-vg
    lv: root
    size: +100%FREE
    resizefs: true