---
- name: Install system packages
  become: true
  apt:
    pkg:
      - parted
    state: latest
    update_cache: true

- name: "Extend partition"
  become: true
  community.general.parted:
    device: /dev/sda
    number: "{{ item }}"
    part_end: "100%"
    resize: true
    state: present
  loop:
    - 2
    - 5

- name: "Expand physical volume"
  become: true
  community.general.lvg:
    vg: debian-vg
    pvs: /dev/sda5
    pvresize: true

- name: "Expand logical volume and resize filesystem"
  become: true
  community.general.lvol:
    vg: debian-vg
    lv: root
    size: "+100%FREE"
    resizefs: true