---
dependencies:
  - role: nvjacobo.caddy
    become: true
    caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
  - role: kyl191.openvpn
    openvpn_topology: subnet
    openvpn_sync_certs: true
    clients: "{{ groups['vpn_clients'] | map('extract', hostvars) | map(attribute='ansible_host') }}"
    openvpn_server_network: 10.11.12.0
    openvpn_push:
      - route 10.11.12.0 255.255.255.0
