---
dependencies:
  - role: nvjacobo.caddy
    become: true
    caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
  - role: kyl191.openvpn
    become: true
    openvpn_topology: subnet
    openvpn_sync_certs: true
    clients:
      - BobEvans
      - BuffaloWildWings
      - CollegeBoard
    openvpn_server_network: 10.11.12.0
    openvpn_push:
      - route 10.11.12.0 255.255.255.0
